default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: root
  password: root

development:
  <<: *default
  database: sample-rails-app_development

test:
  <<: *default
  database: sample-rails-app_test

production:
  <<: *default
  database: sample-rails-app_production
